config/routes.rb
RorEcommerceDev::Application.routes.draw do

  get "tweets/index"

  get "tweets/new"

  get "tweets/create"
  get "tweets/get_tweets"
  get "tweets/get_list_of_connected_users"
  match '/vote_image/:photo_id' => 'tweets#vote_image',:as => "vote_image"
  match '/view_most_voted_page' => 'tweets#view_most_voted_page',:as => "view_most_voted_page"
  match "/tweets/:screen_name/" => "tweets#user_profile",:as => 'user_profile'
  resources :atricles
  root :to => 'welcome#index'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match "/auth/:provider/callback" => "sessions#create"
  match "/signout" => "sessions#destroy", :as => :signout

end

app/models/atricle.rb
class Atricle < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
 require 'rubygems'
 require 'twitter'

 attr_accessible :from_user, :from_user_id_str, :profile_image_url, :text, :twitter_created_at,:user_id
 belongs_to :user
 
 #var twimg = /twimg.com\/([a-z-A-Z0-9]*).jpg/
 #tweet.entities.media[i].media_url



    #A method to grab latest tweets from Twitter
  def self.get_latest_tweets(user_id)

     @user= User.find(user_id)
    @twitter=  @user.twitter.home_timeline()
   # @twitter =  Twitter.home_timeline(:count => 10)
     @twitter.each do |tweet_results|

     #finally creating the tweet record
      unless Tweet.exists?(['twitter_created_at = ? AND from_user_id_str = ?',tweet_results.created_at.to_datetime, tweet_results.id.to_s])

      linked = tweet_results.text.gsub( %r{http://[^\s<]+} ) do |url|
     
      # linked = tweet_results.text.gsub( %r{pic.twitter.com/+} ) do |url|
      if  url
      if tweet_results.media[0]
          UserProfile.create!({
         :profile_image_url => tweet_results.profile_image_url,
         :image_url => tweet_results.media[0].media_url ,
         :user_id => user_id
       })
      
      end
     
       Tweet.create!({
        :from_user => tweet_results.from_user,
        :from_user_id_str => tweet_results.id,
        :profile_image_url => tweet_results.profile_image_url,
        :text => tweet_results.text,
        :twitter_created_at => tweet_results.created_at.to_datetime,
        #:user_name => tweet_results.auth["info"]["from_user"]
         :user_id => user_id
       })
       end
      end
    end
   end #unless end
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  has_many :tweets  
  has_many :user_profiles

def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["info"]["name"]
    user.profile_image = auth['info']['image'] 
    user.oauth_token = auth.credentials.token
    user.oauth_secret = auth.credentials.secret

  end
end


def twitter
  @twitter ||= Twitter::Client.new(oauth_token: oauth_token, oauth_token_secret: oauth_secret)
end




end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
   attr_accessible :profile_image_url,:user_id,:image_url
   belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  private
 
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
  auth = request.env["omniauth.auth"]
  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
  session[:user_id] = user.id
  redirect_to root_url, :notice => "Signed in!"
 end

 def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Signed out!"
 end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
#  before_filter :get_tweets
  layout 'site'
  require 'rubygems'
  require 'twitter'
  def index
    @tweets = Tweet.find(:all,:conditions=>["user_id =?",current_user.id],:order =>"twitter_created_at desc",:limit => 10)
  end

  def new
  end

  def create
  end
   
  def get_tweets

    Tweet.get_latest_tweets(current_user.id)
    respond_to do |format|
      format.html { redirect_to tweets_index_path }
      format.json { head :no_content }
    end
   
  end

  def get_list_of_connected_users
   @tweets = Tweet.paginate(:conditions=>["user_id =?",current_user.id],:page => params[:page], :per_page => 5)
  end

  def user_profile
   @user_photos = UserProfile.find(:all,:conditions=>["user_id =?",current_user.id],:limit => 10,:order =>"created_at desc")
  end

 def vote_image
 
  @photo =  UserProfile.find_by_id(params[:photo_id])
  if @photo.vote != nil
     @photo.vote =  @photo.vote.to_i + 1 
  else
    @photo.vote = "1"
  end
  if @photo.save!
  
     if  request.xhr?
        render :partial => 'vote_image' 
     
     end
  end
  
  # respond_to do |format|
   #   format.html { redirect_to user_profile_path }
   #   format.json { head :no_content }
   # end

 end

 def view_most_voted_page
     @user_photos = UserProfile.find(:all,:conditions=>["user_id =?",current_user.id],:order => "vote desc")
 end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 layout :layout_by_resource
  def index
  end
  private


  def layout_by_resource
    if current_user
      "site"
    else
      "application"
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atricles_helper.rb
module AtriclesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  #convert the plain links into HTML anchor links (with <a> tags) and return the string back
  #uses String's gsub method for regular expression
  def display_content_with_links(text)
     text.gsub(/(http:\/\/[a-zA-Z0-9\/\.\+\-_:?&=]+)/) {|a| "<a href=\"#{a}\" target='_blank'>#{a}</a>"}
      linked = text.gsub( %r{http://[^\s<]+} ) do |url|
         puts url.inspect
      end
  end
	 

end

app/views/atricles/_form.html.erb
<%= form_for(@atricle) do |f| %>
  <% if @atricle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atricle.errors.count, "error") %> prohibited this atricle from being saved:</h2>

      <ul>
      <% @atricle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/atricles/edit.html.erb
<h1>Editing atricle</h1>

<%= render 'form' %>

<%= link_to 'Show', @atricle %> |
<%= link_to 'Back', atricles_path %>

app/views/atricles/index.html.erb
<h1>Listing atricles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @atricles.each do |atricle| %>
  <tr>
    <td><%= atricle.name %></td>
    <td><%= atricle.description %></td>
    <td><%= link_to 'Show', atricle %></td>
    <td><%= link_to 'Edit', edit_atricle_path(atricle) %></td>
    <td><%= link_to 'Destroy', atricle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Atricle', new_atricle_path %>

app/views/atricles/new.html.erb
<h1>New atricle</h1>

<%= render 'form' %>

<%= link_to 'Back', atricles_path %>

app/views/atricles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @atricle.name %>
</p>

<p>
  <b>Description:</b>
  <%= @atricle.description %>
</p>


<%= link_to 'Edit', edit_atricle_path(@atricle) %> |
<%= link_to 'Back', atricles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorEcommerceDev</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main">
  <div class="home-cl">
    <p>Test Application <br />
      Upload for Android or <br />
      <a href="#">eSiteWorld.com</a></p>
      <%= link_to "Sign in with Twitter", "/auth/twitter" %>  </div>
</div>
<%= yield %>

</body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RorEcommerceDev</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>

<div id="main">
  <div class="admin-inner1">
    <div class="admin-top">
      <div class="ad-sign"><span>Welcome <%= current_user.name %>, <%= link_to "Sign Out", signout_path %></span></div>
  <div class="ad-sign"><span><%= link_to "Click Here To Get Recenly Posted Tweets",tweets_get_tweets_path %></span></div>
   
      <div class="dow">   <span>  <%= link_to "10 Latest Tweets Listing With Images",tweets_index_path %> | <%=link_to "List Of Connected Users (My Followers)",tweets_get_list_of_connected_users_path %> | <%= link_to "My Profile & My Top Voted Images",user_profile_path(current_user.name)%> </span></div>
    </div>
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/tweets/_vote_image.js.erb
$("#vote_data").html("<%= escape_javascript(render :text=>'sucessfully voted') %>"); // replace the "results" div with the results

app/views/tweets/create.html.erb
<h1>Tweets#create</h1>
<p>Find me in app/views/tweets/create.html.erb</p>

app/views/tweets/get_list_of_connected_users.html.erb
<div class="admin-page-lis"><span>List of Connected User</span></div>
<div class="admin-bot-lis">   
<% if @tweets %>
  <% @tweets.each do |tweet| %>
  <table width="100%" border="0" cellpadding="7" cellspacing="0"  class="ad-table1">
    <tr>
      <td width="90"><table border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td align="center"> <%= link_to image_tag(tweet.profile_image_url, :border=>0), :class => 'blanck-img' %></td>
    </tr>
    </table></td>
          <td valign="top"><table border="0" cellpadding="0" cellspacing="0">
              <tr>
                <td class="date"><span>Name: <em> <%= link_to tweet.from_user, "http://twitter.com/#{tweet.from_user}", :class => "username", :target => "_blank" %></em></span> </td>
              </tr>
            </table></td>
      
        </tr>
      </table>
     <% end %>
<% end%>
  <%= will_paginate @tweets %>
</div>

app/views/tweets/index.html.erb
<div class="admin-page-lis"><span>Latest 10 Tweets of <%= current_user.name%></span></div>
<div class="admin-bot-lis">
  <% if @tweets %>
  <% @tweets.each do |tweet| %>
    <table width="100%" border="0" cellpadding="7" cellspacing="0"  class="ad-table1">
      <tr>
        <td width="90">
          <table border="0" cellpadding="0" cellspacing="0">
            <tr>
              <td align="center"><%= link_to image_tag(tweet.profile_image_url), :class => 'blanck-img' %><br />
               <%=tweet.from_user%></td>
            </tr>
            </table>
         </td>
          <td valign="top">
          <table border="0" cellpadding="0" cellspacing="0">
              <tr>
                  <td class="date"><span>Tweet: <em><%= tweet.text %></em></span> <span>Date <em> <%=  tweet.twitter_created_at.to_date %> </span> </td>
              </tr>
            </table>
            </td>
        </tr>
      
 </table>
 <% end %>
<% end%>
</div>

app/views/tweets/new.html.erb
<h1>Tweets#new</h1>
<p>Find me in app/views/tweets/new.html.erb</p>

app/views/tweets/user_profile.html.erb
<div class="admin-bot-lis">
  <% if @user_photos %>
    <table width="100%" border="0" cellpadding="7" cellspacing="0"  class="ad-table10">
      <tr>
        <th align="left"><a style="float:left;" title="test" href="<%=current_user.profile_image.gsub("_normal", "") rescue nil%>" rel="lightbox">
        <img src="<%=current_user.profile_image rescue nil%>" class="blanck1"/></a></th>
        <img src="current_user.twitter.user.profile_image_url rescue nil" class="blanck1"/>
        <th valign="top" align="left">Name: <%= current_user.name %></th>
        <th valign="top" colspan="2"><%= link_to "View Most Voted Image",view_most_voted_page_path%></th>
      </tr>
         <% @user_photos.each_with_index do |user_photo, index| %>
         <% i= index%4 %>
         <% if i == 0 %>      <tr> <% end %>
        <%# @user_photos.each do |user_photo| %>
       
        <td valign="top" width="289">
           <div class ="image-pro">
           <%= link_to image_tag(user_photo.image_url, :border=>0), :class => 'blanck1 blanck2' %>  <br />
           </div>
             <span>Vote: <%= user_photo.vote rescue nil%></span>
            <%= link_to "Vote Now",vote_image_path(user_photo.id), :class => "vote", :remote => true %></a>
              <span id ="vote_data">
               
            </span>
         </td>
         <% if i == 3 %>      </tr> <% end %> 
 <% end %>
    </table>
  <% end %>
</div>
  

<script language ="javascript" type="text/javascript">
 function getvote()
{
alert("hello");
var photo_id = $('#photo_id').val();
alert(photo_id);



  var form = $("#vote_image_form"); // grab the form wrapping the search bar.
  var url = "/vote_image"; // appointment_search action.  
  var formData = form.serialize(); // grab the data in the form  
  $.post(url, formData, function(html) { // perform an AJAX get
    
      
  });
}
</script>

app/views/tweets/view_most_voted_page.html.erb
<div class="admin-bot-lis">
<table width="100%" border="0" cellpadding="7" cellspacing="0"  class="ad-table10">
  <%  @user_photos.each do |user_photo| %>
<%if user_photo.vote %>
 <tr>
 <td width="289">
    <div class ="image-pro">
           <%= link_to image_tag(user_photo.image_url, :border=>0), :class => 'blanck1' %>  <br />
    </div>
</td>
<td style="align="left" valign="top"">
  Vote:  <%= user_photo.vote rescue nil %>
</td>
  </tr>

<% end %>
  <% end%>
</div>